Repository codehood-org/mentors-website, pull requests merged in 2020-10, with the labels that each got.

#2 fix format issue
  README.md
Labels: hacktoberfest-accepted

#15 Create Mui App Bar contains title & switch mode
  src/App.js
Labels: hacktoberfest-accepted

#22 feat: fetch mentor image from twitter handler
  LICENSE
  README.md
  src/controllers/mentor-card/MentorCard.js
  src/data/mentors.json
Labels: hacktoberfest-accepted

#23 Makes Dark Mode Switcher functional. Fixes #21
  src/App.js
Labels: feature, hacktoberfest-accepted

#27 Create CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#32 Use localStorage to save hearted mentors. Solves #10
  src/App.js
  src/controllers/mentor-card/MentorCard.js
  src/data/mentors.json
  src/hooks/useLocalStorageToggle.js
Labels: hacktoberfest-accepted

#40 Change app title
  public/index.html
Labels: hacktoberfest-accepted

#43 Create switch btn to toggle favorite mentors
  src/App.js
  src/controllers/mentor-filter/MentorFilter.js
Labels: hacktoberfest-accepted

#37 [#35] Persist light/dark mode in localstorage
  src/App.js
Labels: hacktoberfest-accepted, hacktoberfest-accepted-and merged

#50 add JSON.parse for the value of the codehood_darkmode localstorage
  src/App.js
Labels: hacktoberfest-accepted

#53 add search by name field
  src/App.js
  src/controllers/mentor-filter/MentorFilter.js
Labels: enhancement, feature, hacktoberfest-accepted

#61 code more redability closing
  README.md
  src/App.js
Labels: hacktoberfest-accepted, hacktoberfest-accepted-and merged

#62 add setup and contribute
  README.md
Labels: hacktoberfest-accepted

#57 Consistent height width card
  src/controllers/mentor-card/MentorCard.js
Labels: enhancement, good first issue, web-design

#68 add brand colors into function createMuiTheme
  src/App.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest-accepted-and merged, web-design

#69 replace dark/light mode text with icon
  src/App.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest-accepted-and merged, web-design

#64 ui-fix: remove horizontal scroll
  src/App.css
  src/App.js
  src/index.css
Labels: bug, enhancement

#71 Logo change
  src/App.js
  src/components/AppHeader.js
  src/images/codehood-logo.jpg
Labels: enhancement, hacktoberfest-accepted, hacktoberfest-accepted-and merged, web-design

#72 Mentorslist
  src/data/mentors.json
Labels: hacktoberfest-accepted, hacktoberfest-accepted-and merged

#74 add clear to mentor name search and add names as drop down
  debug.log
  src/controllers/mentor-filter/MentorFilter.js
Labels: hacktoberfest-accepted
